title: My blog
description: A blog dedicated to MLB and NCAA baseball analysis
author: "Colin Sanders"

theme: minima

base_url: 
repository: ColinSanders1/ColinSanders1.github.io

# Minima social links
github_username: ColinSanders1
linkedin_username: colin-sanders-14302521a

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
